language: julia
dist: xenial
python:
  - "3.7"
git:
  depth: 3
  quiet: true
julia:
  - 1.3
os:
  - osx
  - linux
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
cache:
  directories:
  - /home/travis/.julia/conda/3/