name = "ADCME"
uuid = "07b341a0-ce75-57c6-b2de-414ffdc00be5"
authors = ["Kailai Xu <kailaix@hotmail.com>"]
version = "0.3.2"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
Conda = ">= 1.3"
FFTW = ">= 1.0"
MAT = ">= 0.5"
Optim = ">= 0.19"
PyCall = ">= 1.91"
PyPlot = ">= 2.8"
Suppressor = ">= 0.1"
julia = ">= 1"

[extras]
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NLopt"]
