name = "ADCME"
uuid = "07b341a0-ce75-57c6-b2de-414ffdc00be5"
authors = ["Kailai Xu <kailaix@hotmail.com>"]
version = "0.7.0"

[deps]
CMake = "631607c0-34d2-5d66-819e-eb0f9aa2061a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CMake = "1.2"
FFTW = "1"
MAT = "0.5,0.6,0.7,0.8,0.9,0.10"
PyCall = "1.91,1.92"
SpecialFunctions = "0.10,1"
julia = "1"

[extras]
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NLopt", "Optim", "PyPlot"]
